# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Unknown, Unbranded
email: dev@uuoffice.cc
description: >- # this means to ignore newlines until "baseurl:"
 Unknown, Unbranded is a creative office established in Peking offering expertise in digital products and working mostly on product Strategy, Branding, UI and space.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

include:
  - public
# Build settings

author:
    name: Unknown, Unbranded
    email: press@uuoffice.cc
    born: 2020-12-30 12:30:23
    location: [ Peking, China ]

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Blog
blog:
    google_analytics: "UA-166822615-2"
    last_modified_at: 2020-12-30 12:30:23

# Jekyll datapage gennerator
page_gen-dirs: true # Specifies whether we want to generate named folders (`true`) or not (`false`) for all generated data.

page_gen: # It's an array specifying a data for which individual pages have to be generated. 
  - data: 'projects.zh'
    template: 'project'
    name: 'title'
    dir: 'zh/work'

  - data: 'projects.en'
    template: 'project'
    name: 'title'
    dir: 'en/work'

  - data: 'projects.fr'
    template: 'project'
    name: 'title'
    dir: 'fr/projets'

# Compress CSS
sass:
    style: compressed

# Plugin
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect

social:
    name: Unknown, Unbranded
    links:
        - '"https://behance.net/unknwon-unbranded"'
        - '"https://www.linkedin.com/in/unknwon-unbranded"'
        - '"https://github.com/unknwon-unbranded"'
        - '"https://behance.net/unknwon-unbranded"'

webmaster_verifications:
    google: "google"
    bing: "bing"
    alexa: ""
    yandex: ""
    baidu: ""

# Cmopress html
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    ignore:
        envs: [local]
    blanklines: false
    profile: false
    startings: [html, head, body]